### ISSUE TITLE
Can not open config file '/usr/share/freeling/config/es'

### ISSUE THREAD

**Issue by froucher** [hfoffani/docker-freeling#1]
Hi @hfoffani,

I am trying to test the docker, but when I launch the example, I get the following messsage:

> Can not open config file '/usr/share/freeling/config/es'.

All help is welcome!

Thx.

> ╰─➤  docker pull herchu/freeling4-es:pub
> pub: Pulling from herchu/freeling4-es
> 51f5c6a04d83: Pull complete 
> d72d5d4601ea: Pull complete 
> a3ed95caeb02: Pull complete 
> Digest: sha256:e6dde4905837f53c811e7d8d6210d37d0bd6beee245a24fba143df4244e071ce
> Status: Downloaded newer image for herchu/freeling4-es:pub
> ╰─➤  echo "Mi casa es bonita." | docker run -i herchu/freeling4-es:pub /usr/bin/analyze -f es
> Can not open config file '/usr/share/freeling/config/es'.

**Comment by hfoffani** [comment]
Weird. The config files are supposedly to be packed inside the docker image.
I'll look at it to figure out what's going on.

**Comment by hfoffani** [comment]
Sorry for the late reply.

The problem is that you need to specify the .cfg extension. It's es.cfg then.

```
$ echo "Mi casa es bonita." | docker run -i herchu/freeling4-es:pub /usr/bin/analyze -f es.cfg
Mi mi DP1CSS 0.999325
casa casa NCFS000 0.998153
es ser VSIP3S0 1
bonita bonito AQ0FS00 1
. . Fp 1
```
